### ISSUE TITLE
The NPC Sheet dont work

### ISSUE THREAD

**Issue by NandoNO82** [astarte-horns/kult-divinity-lost#10]
When I try to use the NPC sheet it dont work. I writte, the sheet save the info, but dont show it.
![Captura de pantalla 2022-05-12 181138](https://user-images.githubusercontent.com/105447565/168121032-bac27367-edd5-4fb9-aef1-d863d478d7e0.jpg)
![Captura de pantalla 2022-05-12 181201](https://user-images.githubusercontent.com/105447565/168121039-a2d66411-cdae-4353-8bb9-f2ef54802969.jpg)
![Captura de pantalla 2022-05-12 181100](https://user-images.githubusercontent.com/105447565/168121044-754c6b13-8d6f-4e2e-8c81-fc87b09e90b1.jpg)

the damage is also not shown, and seems to be erased

**Comment by astarte-horns** [comment]
Which version of the software are you running?
Is the version 1.3.0?

I can't find this sheet.

**Comment by NandoNO82** [comment]
It seems I have a problem with the auto update. 

Thanks and sorry!

**Comment by NandoNO82** [comment]
1.3.1 now. I found the sheet like I show you in the images. Only the names are translate.
![Captura de pantalla 2022-05-16 200917](https://user-images.githubusercontent.com/105447565/168656574-b6abbbd7-359e-4514-9cb8-fef851c3feee.jpg)
![Captura de pantalla 2022-05-16 201144](https://user-images.githubusercontent.com/105447565/168656581-b31d1cc8-c4f1-4d47-96d9-b34ff0be5310.jpg)
"Hoja por defecto" is "Default Sheet"

What sheet do you use for NPCs?

**Comment by NandoNO82** [comment]
> @NandoNO82 found a a problem with the auto update. Thanks and sorry!

Hello astarte. Read the other messages. It's not the problem
