### ISSUE TITLE
Invalid manifest file

### ISSUE THREAD

**Issue by ghorbey** [astarte-horns/kult-divinity-lost#3]
Hi,

I have an error when updating the game system : "The request https://github.com/astarte-horns/kult-divinity-lost/blob/main/system.json did not provide a valid manifest file."

Have a good day.

**Comment by Varstahl** [comment]
The manifest points to the github page, instead of the raw file itself: https://raw.githubusercontent.com/astarte-horns/kult-divinity-lost/main/system.json

**Comment by astarte-horns** [comment]
fixing line "version": "1.2.2",
