### ISSUE TITLE
Undefined Rolls and Inaccurate Move Outcomes

### ISSUE THREAD

**Issue by patrickburk1988** [astarte-horns/kult-divinity-lost#4]
When clicking a move to roll it, the roll result is always displayed as `undefined`, and the move outcome is always treated as a partial success. This happens no matter the dice roll or the final result. For example, here is a character with a +3 Perception who rolled a 16 on the dice:
![](https://i.imgur.com/oCP3PSK.png)

The 16 and +3 modifier for Perception are registered correctly on the dice hover, however:
![](https://i.imgur.com/KvLZbnH.png)

I had this same problem with the 1.1 version of the Kult system. I'm running Foundry 9 on Forge, with a new game and no modules enabled.

Edit: The console shows the following warning when clicking a move to roll it: `Roll#evaluate is becoming asynchronous. In the short term you may pass async=true or async=false to evaluation options to nominate your preferred behavior.` Dunno if this would affect the chat log output.

**Comment by astarte-horns** [comment]
Fixed 1.2.2
