### ISSUE TITLE
Possible spanish translation collaboration

### ISSUE THREAD

**Issue by SeregilB** [astarte-horns/kult-divinity-lost#5]
Hello there!

Some colleagues and myself have worked on the translation of your system into Spanish, as well as on a module with some compendiums that are very useful for running KDL games in Foundry VTT. Would you be interested on including any of these into your system development? If you are, just drop me a line and we can discuss it further via email or through any other channel.

Thanks a lot. Take care!
Seregil

**Comment by astarte-horns** [comment]
Hi!

It would be a great collaboration!

Waiting for your contact!

astarte-horns

**Comment by SeregilB** [comment]
Hello!

Thanks for your reply, that's excellent.

Not sure if you use Discord, but if you do, you can add me there if you want: Seregil#5949

Alternatively, I can give you my email address if you prefer.

Thanks.
Seregil

**Comment by astarte-horns** [comment]
Hello

This is the file with the English language.

https://github.com/astarte-horns/kult-divinity-lost/blob/main/lang/en.json

Just copy it and make a 

es.json

with your translation.

I added you to my Discord. But I prefer to talk by email.

Best regards,

**Comment by astarte-horns** [comment]
Hello. I left my email on discord.
